spring.application.name=DBS-PROJ

# Database Connection (Adjust host/port/credentials as needed)
spring.datasource.url=jdbc:mariadb://localhost:3306/db_sols
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
